C     DOUBLE-PRECISION BLAS ADAPTERS FOR THE OPT-IN MISHKA_REAL8 BUILD.
C     THE HISTORICAL SOURCE USES SINGLE-PRECISION BLAS NAMES EVEN WHEN ITS
C     DEFAULT REAL AND COMPLEX KINDS ARE PROMOTED BY THE COMPILER.

      SUBROUTINE SCOPY(N,SX,INCX,SY,INCY)
      INTEGER N,INCX,INCY
      DOUBLE PRECISION SX(*),SY(*)
      CALL DCOPY(N,SX,INCX,SY,INCY)
      RETURN
      END

      SUBROUTINE SSCAL(N,SA,SX,INCX)
      INTEGER N,INCX
      DOUBLE PRECISION SA,SX(*)
      CALL DSCAL(N,SA,SX,INCX)
      RETURN
      END

      SUBROUTINE CCOPY(N,CX,INCX,CY,INCY)
      INTEGER N,INCX,INCY
      COMPLEX*16 CX(*),CY(*)
      CALL ZCOPY(N,CX,INCX,CY,INCY)
      RETURN
      END

      SUBROUTINE CSCAL(N,CA,CX,INCX)
      INTEGER N,INCX
      COMPLEX*16 CA,CX(*)
      CALL ZSCAL(N,CA,CX,INCX)
      RETURN
      END

      SUBROUTINE CAXPY(N,CA,CX,INCX,CY,INCY)
      INTEGER N,INCX,INCY
      COMPLEX*16 CA,CX(*),CY(*)
      CALL ZAXPY(N,CA,CX,INCX,CY,INCY)
      RETURN
      END

      COMPLEX*16 FUNCTION CDOTC(N,CX,INCX,CY,INCY)
      INTEGER N,INCX,INCY
      COMPLEX*16 CX(*),CY(*),ZDOTC
      EXTERNAL ZDOTC
      CDOTC=ZDOTC(N,CX,INCX,CY,INCY)
      RETURN
      END

      COMPLEX*16 FUNCTION CDOTU(N,CX,INCX,CY,INCY)
      INTEGER N,INCX,INCY
      COMPLEX*16 CX(*),CY(*),ZDOTU
      EXTERNAL ZDOTU
      CDOTU=ZDOTU(N,CX,INCX,CY,INCY)
      RETURN
      END

      DOUBLE PRECISION FUNCTION SCASUM(N,CX,INCX)
      INTEGER N,INCX
      COMPLEX*16 CX(*)
      DOUBLE PRECISION DZASUM
      EXTERNAL DZASUM
      SCASUM=DZASUM(N,CX,INCX)
      RETURN
      END

      INTEGER FUNCTION ICAMAX(N,CX,INCX)
      INTEGER N,INCX,IZAMAX
      COMPLEX*16 CX(*)
      EXTERNAL IZAMAX
      ICAMAX=IZAMAX(N,CX,INCX)
      RETURN
      END
